# Generated by Django 2.2.6 on 2019-11-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessnumbers',
            name='name',
            field=models.CharField(default='test', max_length=24),
            preserve_default=False,
        ),
    ]
